#ifndef _MAIN_H_
#define _MAIN_H_

/*
PERIPHERALS	MODES	FUNCTIONS	PINS
ADC	IN2	ADC_IN2	PC4
I2C	I2C	I2C_SCL	PB4
I2C	I2C	I2C_SDA	PB5
SYS	SWIM Input and Output	SYS_SWIM	PD1
TIM1	Output CH3	TIM1_CH3	PC3
UART1	Asynchronous	UART1_RX	PD6
UART1	Asynchronous	UART1_TX	PD5

Pin Nb	PINs	FUNCTIONs	LABELs
1	PD4	GPIO_Output	COM3
2	PD5	UART1_TX	
3	PD6	UART1_RX	
5	PA1	GPIO_Output	BTN1
6	PA2	GPIO_Output	BTN2
10	PA3	GPIO_Output	BTN3
11	PB5	I2C_SDA	
12	PB4	I2C_SCL	
13	PC3	TIM1_CH3	
14	PC4	ADC_IN2	
15	PC5	GPIO_Output	LED1
16	PC6	GPIO_Output	LED2
17	PC7	GPIO_Output	LED3
18	PD1	SYS_SWIM	
19	PD2	GPIO_Output	COM1
20	PD3	GPIO_Output	COM2
*/

/* Green */
#define COM1_PORT GPIOD
#define COM1_PIN  GPIO_PIN_2
#define COM2_PORT GPIOD
#define COM2_PIN  GPIO_PIN_3
#define COM3_PORT GPIOD
#define COM3_PIN  GPIO_PIN_4

/* Red */
#define LED1_PORT GPIOC
#define LED1_PIN  GPIO_PIN_5
#define LED2_PORT GPIOC
#define LED2_PIN  GPIO_PIN_6
#define LED3_PORT GPIOC
#define LED3_PIN  GPIO_PIN_7

/* Black */
#define BTN1_PORT GPIOA
#define BTN1_PIN  GPIO_PIN_1
#define BTN2_PORT GPIOA
#define BTN2_PIN  GPIO_PIN_2
#define BTN3_PORT GPIOA
#define BTN3_PIN  GPIO_PIN_3

#endif
